---
title: "MetIDTracker documentation website"
output: 
  html_document:
    toc: FALSE
---

# Introduction

Large-scale mass-spectrometry based metabolomics experiments became a common place in recent years. Data analysis for such experiments is a complex multi-step process which presents a number of challenges in quality control, within and between-batch normalization, proper alignment of mass-spectral features between the samples, dealing with missing data, identification of unknowns, removal of redundant signals, data integration from multiple assays, etc. It requires the use of multiple software tools, often with heavy emphasis on custom scripts and complex pipelines. The goal of this project is to put an intuitive user interface on a number of the common tasks in metabolomics data analysis in order to better organize and streamline the procedure.

##	Downloads
###	Software & database
- [MetIDTracker software](https://drive.google.com/file/d/1Nm0D2ZFocODAMzZuJ2lleXeHMy5ZULuO/view?usp=sharing)
- [PostgreSQL database dump](https://drive.google.com/file/d/15smKw8Xo5D8xQDA8TkKg8icQ_EWqZFzr/view?usp=sharing)


